name: Deploy to EC2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & Push backend
      run: |
        cd backend
        docker build -t arieling/pokemon-backend .
        docker push arieling/pokemon-backend

    - name: Build & Push frontend
      run: |
        cd frontend
        docker build -t arieling/pokemon-frontend .
        docker push arieling/pokemon-frontend

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          /usr/bin/docker pull arieling/pokemon-backend
          /usr/bin/docker pull arieling/pokemon-frontend
          /usr/bin/docker stop backend || true && /usr/bin/docker rm backend || true
          /usr/bin/docker stop frontend || true && /usr/bin/docker rm frontend || true
          /usr/bin/docker run -d -p 3000:3000 --name backend arieling/pokemon-backend
          /usr/bin/docker run -d -p 3001:3000 --name frontend arieling/pokemon-frontend

